language: dart
sudo: required
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - sudo cp ci/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -c 'create database dart_test;' -U postgres
  - psql -c 'create user dart with createdb;' -U postgres
  - psql -c "alter user dart with password 'dart';" -U postgres
  - psql -c 'grant all on database dart_test to dart;' -U postgres
  - psql -c 'create user darttrust with createdb;' -U postgres
  - psql -c 'grant all on database dart_test to darttrust;' -U postgres
  - pub get
script: pub run test -j 1 -r expanded
branches:
  only:
    - master