name: postgres
description: A library to connect and query PostgreSQL databases.
version: 0.9.2
author: stable|kernel <jobs@stablekernel.com>
homepage: https://github.com/stablekernel/postgresql-dart
documentation:

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  crypto: "^2.0.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
