name: postgres
description: PostgreSQL database driver. Supports statement reuse and binary protocol and connection pooling.
version: 3.0.7
homepage: https://github.com/isoos/postgresql-dart
topics:
  - sql
  - db
  - database
  - postgres

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  buffer: ^1.2.2
  crypto: ^3.0.0
  collection: ^1.15.0
  sasl_scram: ^0.1.0
  stream_channel: ^2.1.1
  async: ^2.10.0
  charcode: ^1.3.1
  meta: ^1.8.0
  pool: ^1.5.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.3.0
  coverage: any
  logging: ^1.2.0
  docker_process: ^1.3.1
  path: ^1.8.0
